### ISSUE TITLE
User info should contain all recipe data

### ISSUE THREAD

**Issue by silverAndroid** [BweakfastClub/Foodora#72]
Since the client doesn't have a local database of recipes being sent by the server, when retrieving user info and getting information such as recipes liked, we will need all the other attributes that come with a recipe like how it's currently done in search

**Comment by koosoku** [comment]
This feature requested was implemented with 
- https://github.com/BweakfastClub/Foodora/pull/80
- https://github.com/BweakfastClub/Foodora/pull/79
